### ISSUE TITLE
Lose slash on windows

### ISSUE THREAD

**Issue by duzc2** [jimmycuadra/shellwords#7]
var command = '"D:\work\arduino\git\ml_agent\avrdude/bin/avrdude" "-CD:\work\arduino\git\ml_agent\avrdude/etc/avrdude.conf" -v  -patmega328p -carduino -PCOM7 -b115200 -D "-Uflash:w:D:\work\arduino\git\ml_agent\tmp/code.ino.hex:i"'
var args = shellwords.split(command);
args:
[ 'D:work\\arduino\\git\\ml_agent\\avrdude/bin/avrdude',
  '-CD:work\\arduino\\git\\ml_agent\\avrdude/etc/avrdude.conf',
  '-v',
  '-patmega328p',
  '-carduino',
  '-PCOM7',
  '-b115200',
  '-D',
  '-Uflash:w:D:work\\arduino\\git\\ml_agent\\tmp/code.ino.hex:i' ]

all the path lost the slash...

**Comment by jimmycuadra** [comment]
The behavior of shellwords is specific to UNIX-like shells, per the description of the project:

> Manipulate strings according to the word parsing rules of the UNIX Bourne shell.

Sorry!
